TRAINING:
  SOFT_AUG: False
  BATCH_SIZE: 10
  TEST_BATCH_SIZE: 10
  N_TRIPLETS: 4
  MIN_KEYPOINTS_PER_IMAGE: 4
  MIN_KEYPOINTS_PER_IMAGE_PAIR: 4
  TRANSFORMER: "PTN"
TEST:
  TEST_BATCH_SIZE: 10
  TRANSFORMER: "PTN"
BLOBINATOR:
  BLOB_SEED: 0x1234
